spring:
  application:
    name: reel2real-backend

  datasource:
    url: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 2
      minimum-idle: 0
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: none   # ðŸ”¥ VERY IMPORTANT
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8000

ors:
  api:
    key: ${ORS_API_KEY}
    url: https://api.openrouteservice.org

nominatim:
  url: https://nominatim.openstreetmap.org

budget:
  ml:
    base-url: https://budget-api-n62a.onrender.com
